# Generated by Django 5.2 on 2025-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingerprintlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Fingerprint Log', 'verbose_name_plural': 'Fingerprint Logs'},
        ),
        migrations.RenameField(
            model_name='fingerprintlog',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='fingerprintlog',
            name='fingerprint',
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='audio_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='canvas_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='color_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='cookie_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='cpu_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='device_memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='do_not_track',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='downlink',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='effective_connection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='fonts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='hardware_concurrency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='orientation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='pdf_viewer_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='pixel_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='plugins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='rtt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='webgl_renderer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='webgl_vendor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintlog',
            name='webrtc_ips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
