# Generated by Django 5.2 on 2025-07-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_fingerprintlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintlog',
            name='connection_type',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fingerprintlog',
            name='downlink',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fingerprintlog',
            name='rtt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
