# Generated by Django 5.2 on 2025-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_fingerprintlog_connection_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishinglog',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='phishinglog',
            name='data',
        ),
        migrations.AddField(
            model_name='phishinglog',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishinglog',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phishinglog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishinglog',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phishinglog',
            name='page',
            field=models.CharField(max_length=100),
        ),
    ]
